[package]
name = "vkjit03"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pretty_env_logger = "0.4.0"
vkjit-core = {path = "libs/vkjit-core"}
vkjit-rust = {path = "libs/vkjit-rust"}
